### ISSUE TITLE
Filtering in the frontend does not work anymore

### ISSUE THREAD

**Issue by yatharthranjan** [RADAR-base/RADAR-Rest-Source-Auth#106]
The filter input does not work anymore with the latest version.

Error in chrome dev as follows-

<a href="https://ibb.co/MpSn7g3"><img src="https://i.ibb.co/K7h6W53/Screenshot-dev.png" alt="Screenshot-dev" border="0"></a>

**Comment by mpgxvii** [comment]
This issue seems to be fixed in the current `dev` branch, but since in this branch we also moved pagination to server side, the filtering only works on the current page. This should then be supported in the backend.

**Comment by yatharthranjan** [comment]
There are a lot of requests for this from the clinical teams, maybe we can prioritise this.

**Comment by yatharthranjan** [comment]
Still getting this issue in version 3.0.0 under certain cases

<a href="https://ibb.co/KNpRDfP"><img src="https://i.ibb.co/5YgtkS0/Screenshot-2021-06-01-at-17-04-43.png" alt="Screenshot-2021-06-01-at-17-04-43" border="0"></a><br /><a target='_blank' href='https://the-crosswordsolver.com/vietnamese-river-or-delta-6-letters'></a><br />

**Comment by blootsvoets** [comment]
Fixed in #143.
