### ISSUE TITLE
Oura Ring Integration

### ISSUE THREAD

**Issue by afolarin** [RADAR-base/RADAR-Rest-Source-Auth#227]
[Oura Ring](https://ouraring.com/)  is an interesting wearable device with a relatively novel location based on the finger rather than the wrist. There are some advantages of this, namely, the fit is tailored so expect better PPG sensor data. Integration is possible via the REST API provided by the vendor. API v2 is the latest implementation and has a number of improvements.
https://cloud.ouraring.com/docs/ 

```[tasklist]
### Tasks
- [ ] https://github.com/RADAR-base/RADAR-Schemas/issues/327
- [ ] https://github.com/RADAR-base/RADAR-REST-Connector/issues/97
```

**Comment by yatharthranjan** [comment]
Yes would be nice to integrate this. Implementation of actual data pull would go in the rest-connector.

**Comment by afolarin** [comment]
Hmm yes, good point shall we move the issue? Or add an issue in `rest-connector` to the task list here?

**Comment by yatharthranjan** [comment]
I think additional issue in rest-connector, as authorization will still be implemented here.

**Comment by yatharthranjan** [comment]
completed in #241
