### ISSUE TITLE
Authorization using Generate URL not working for Garmin

### ISSUE THREAD

**Issue by yatharthranjan** [RADAR-base/RADAR-Rest-Source-Auth#234]
Authorization using the link generated from Generate URL button for Garmin source-type does not work. This works for Fitbit source type.

Not much info in the logs- 

```
ERROR - [407] GET registrations/08APtrwC8WZev_hW7wddrq4h/authorize - user_unauthorized: Access token can not be retrieved (HttpApplicationExceptionMapper.kt:30)
```

<img width="1261" alt="image" src="https://github.com/RADAR-base/RADAR-Rest-Source-Auth/assets/11093544/0ef3eacc-eaa6-439c-8dbb-2c97d617aacd">

here is the url format - 

```
https://trials.radar-base.net/rest-sources/authorizer/users:new?state=KyWl94iZjNL55zem4mSizbcr&oauth_token=84xxxxxxx-79ee-xxxxxxxx-91bxxxxxxxx4ae5&oauth_verifier=MiVxxxx3C
```

**Comment by blootsvoets** [comment]
Fixed by #235
