### ISSUE TITLE
Add dockerhub token to organization

### ISSUE THREAD

**Issue by Bdegraaf1234** [RADAR-base/RADAR-Rest-Source-Auth#273]
Since we are now encountering [problems in our CI/CD](https://github.com/RADAR-base/RADAR-Rest-Source-Auth/pull/272), it would be good to add a dockerhub token [to our organization](https://github.com/organizations/RADAR-base/settings/secrets/actions/DOCKERHUB_TOKEN)

I will make a branch which uses the organization secret DOCKERHUB_TOKEN but I do not have access to the credentials currently, so if someone can edit the secret and add a token that would solve it I believe? Otherwise we may have to add a DOCKERHUB_USERNAME secret as well.

In addition, while we are at it we should probably migrate the SNYK_TOKEN there as well

https://github.com/RADAR-base/RADAR-Rest-Source-Auth/pull/272

**Comment by Bdegraaf1234** [comment]
I actually looks like dependabot just [does not have access to the secrets](https://github.com/dependabot/dependabot-core/issues/3253)... @yatharthranjan or @mpgxvii could you or someone add these secrets [here as well](https://github.com/organizations/RADAR-base/settings/secrets/dependabot)?

I don't really understand how the other repos do it right now tbh.

github organization secrets are automatically used, so if we add the organization secrets we can just start removing the repo-secrets without any need for code changes.

**Comment by yatharthranjan** [comment]
The issue is that most of these tokens are user-scoped, and hence, using them at the org level is not ideal. I noticed there are plans to add [org-scoped token](https://github.com/docker/roadmap/issues/461) to DockerHub, which would be great. We can keep an eye on that issue.
In the meantime, I will add my personal access token to the org.
