### ISSUE TITLE
Add authorization with Management portal using `authorization-code`

### ISSUE THREAD

**Issue by nivemaham** [RADAR-base/RADAR-Rest-Source-Auth#32]
We need a systematic way to authenticate users for rest-auth.
We have to add support to login with Management Portal auth using `authorization-code` flow. 
@mpgxvii would you be able to take a look at the front-end side?
@yatharthranjan @blootsvoets Have we done anything on this topic? I guess not yet. Am I right?

**Comment by yatharthranjan** [comment]
@nivemaham no we have not made any start on this yet but it is listed as one of the points in issue #13

**Comment by yatharthranjan** [comment]
We can use the [radar-spring](https://github.com/RADAR-base/radar-spring) library to provide authorization in the backend.

**Comment by blootsvoets** [comment]
This was fixed with #55.
