### ISSUE TITLE
Add RESET capability for re-pulling data

### ISSUE THREAD

**Issue by yatharthranjan** [RADAR-base/RADAR-Rest-Source-Auth#33]
we need a RESET button which will allow for the connector to pull all the historic data for the user again.
As specified in https://github.com/RADAR-base/RADAR-REST-Connector/pull/50 which creates a unique id using the existing user id and a new version (`new id = user id + # + version` if version is not null), we need to add a `version` property to the user and increment it each time it is RESET. For the first instance, this should be `null`, so as to make it backward compatible with the ids in the current connector offsets.

**Comment by blootsvoets** [comment]
Note that version does not have to be a number, it can also be an ISO date-time (making the reset time traceable). As long as it is unique between resets.

**Comment by yatharthranjan** [comment]
@blootsvoets @nivemaham Is there someway of specifying this per-topic or per datastream? (For example, if one only wants to repull `intraday_steps` for a particular participant)

**Comment by nivemaham** [comment]
Reset per participant has been implemented in #40 
Closed by #50  
Released in 1.3.0
